baseURL= "/"
languageCode= "en"
title= "Alex's Blog"
paginate = 5
copyright = "All rights reserved - 2018"
theme = "hugo-theme-casper"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  description = "A blog for tech and tech-adjacent ramblings"
  metadescription = ""
  cover = ""
  author = "Alexander Reynolds"
  authorlocation = "Earth, Milky Way Galaxy"
  authorwebsite = ""
  authorbio= ""
  logo = ""
  hjsStyle = "default"
  paginatedsections = ["posts"]